import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import RootLayoutClient from "./RootLayoutClient";
import { Analytics } from "@vercel/analytics/next"
import "./globals.css";

const figtree = Figtree({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Circl",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/circl.png?v=1", sizes: "32x32", type: "image/png" },
      { url: "/circl.png?v=1", sizes: "16x16", type: "image/png" },
    ],
    shortcut: "/circl.png?v=1",
    apple: "/circl.png?v=1",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={figtree.variable}>
      <body>
        <RootLayoutClient>
          {children}
          <Analytics />
        </RootLayoutClient>
      </body>
    </html>
  );
}
